export const CHANNEL_CREATE_REQUEST = 'CHANNEL_CREATE_REQUEST';
export const CHANNEL_CREATE_SUCCESS = 'CHANNEL_CREATE_SUCCESS';
export const CHANNEL_CREATE_FAILURE = 'CHANNEL_CREATE_FAILURE';

export const UPLOAD_LOGO_REQUEST = 'UPLOAD_LOGO_REQUEST';
export const UPLOAD_LOGO_SUCCESS = 'UPLOAD_LOGO_SUCCESS';
export const UPLOAD_LOGO_FAILURE = 'UPLOAD_LOGO_FAILURE';

export const LIMITS_REQUEST = 'LIMITS_REQUEST';
export const LIMITS_SUCCESS = 'LIMITS_SUCCESS';
export const LIMITS_FAILURE = 'LIMITS_FAILURE';

export const CHANNEL_LIST_REQUEST = 'CHANNEL_LIST_REQUEST';
export const CHANNEL_LIST_SUCCESS = 'CHANNEL_LIST_SUCCESS';
export const CHANNEL_LIST_FAILURE = 'CHANNEL_LIST_FAILURE';

export const CHANNEL_DETAILS_REQUEST = 'CHANNEL_DETAILS_REQUEST';
export const CHANNEL_DETAILS_SUCCESS = 'CHANNEL_DETAILS_SUCCESS';
export const CHANNEL_DETAILS_FAILURE = 'CHANNEL_DETAILS_FAILURE';

export const CHANNEL_DETAILS_UPDATE_REQUEST = 'CHANNEL_DETAILS_UPDATE_REQUEST';
export const CHANNEL_DETAILS_UPDATE_SUCCESS = 'CHANNEL_DETAILS_UPDATE_SUCCESS';
export const CHANNEL_DETAILS_UPDATE_FAILURE = 'CHANNEL_DETAILS_UPDATE_FAILURE';

export const CHANNEL_LIMITS_REQUEST = 'CHANNEL_LIMITS_REQUEST';
export const CHANNEL_LIMITS_SUCCESS = 'CHANNEL_LIMITS_SUCCESS';
export const CHANNEL_LIMITS_FAILURE = 'CHANNEL_LIMITS_FAILURE';

export const LEAVE_CHANNEL_REQUEST = 'LEAVE_CHANNEL_REQUEST';
export const LEAVE_CHANNEL_SUCCESS = 'LEAVE_CHANNEL_SUCCESS';
export const LEAVE_CHANNEL_FAILURE = 'LEAVE_CHANNEL_FAILURE';

export const CHANNEL_DELETE_REQUEST = 'CHANNEL_DELETE_REQUEST';
export const CHANNEL_DELETE_SUCCESS = 'CHANNEL_DELETE_SUCCESS';
export const CHANNEL_DELETE_FAILURE = 'CHANNEL_DELETE_FAILURE';

export const CHANNEL_MEMBERS_REQUEST = 'CHANNEL_MEMBERS_REQUEST';
export const CHANNEL_MEMBERS_SUCCESS = 'CHANNEL_MEMBERS_SUCCESS';
export const CHANNEL_MEMBERS_FAILURE = 'CHANNEL_MEMBERS_FAILURE';

export const CHANNEL_MEMBERS_DELETE_REQUEST = 'CHANNEL_MEMBERS_DELETE_REQUEST';
export const CHANNEL_MEMBERS_DELETE_SUCCESS = 'CHANNEL_MEMBERS_DELETE_SUCCESS';
export const CHANNEL_MEMBERS_DELETE_FAILURE = 'CHANNEL_MEMBERS_DELETE_FAILURE';

export const CHANNEL_INVITATION_LIST_REQUEST = 'CHANNEL_INVITATION_LIST_REQUEST';
export const CHANNEL_INVITATION_LIST_SUCCESS = 'CHANNEL_INVITATION_LIST_SUCCESS';
export const CHANNEL_INVITATION_LIST_FAILURE = 'CHANNEL_INVITATION_LIST_FAILURE';

export const CHANNEL_INVITATION_SEND_REQUEST = 'CHANNEL_INVITATION_SEND_REQUEST';
export const CHANNEL_INVITATION_SEND_SUCCESS = 'CHANNEL_INVITATION_SEND_SUCCESS';
export const CHANNEL_INVITATION_SEND_FAILURE = 'CHANNEL_INVITATION_SEND_FAILURE';

export const CHANNEL_INVITATION_RESEND_REQUEST = 'CHANNEL_INVITATION_RESEND_REQUEST';
export const CHANNEL_INVITATION_RESEND_SUCCESS = 'CHANNEL_INVITATION_RESEND_SUCCESS';
export const CHANNEL_INVITATION_RESEND_FAILURE = 'CHANNEL_INVITATION_RESEND_FAILURE';

export const CHANNEL_INVITATION_CANCEL_REQUEST = 'CHANNEL_INVITATION_CANCEL_REQUEST';
export const CHANNEL_INVITATION_CANCEL_SUCCESS = 'CHANNEL_INVITATION_CANCEL_SUCCESS';
export const CHANNEL_INVITATION_CANCEL_FAILURE = 'CHANNEL_INVITATION_CANCEL_FAILURE';

export const CHANNEL_SETTINGS_REQUEST = 'CHANNEL_SETTINGS_REQUEST';
export const CHANNEL_SETTINGS_SUCCESS = 'CHANNEL_SETTINGS_SUCCESS';
export const CHANNEL_SETTINGS_FAILURE = 'CHANNEL_SETTINGS_FAILURE';

export const CHANNEL_SETTINGS_UPDATE_REQUEST = 'CHANNEL_SETTINGS_UPDATE_REQUEST';
export const CHANNEL_SETTINGS_UPDATE_SUCCESS = 'CHANNEL_SETTINGS_UPDATE_SUCCESS';
export const CHANNEL_SETTINGS_UPDATE_FAILURE = 'CHANNEL_SETTINGS_UPDATE_FAILURE';

export const CHANNEL_MUTE_ACTION_REQUEST = 'CHANNEL_MUTE_ACTION_REQUEST';
export const CHANNEL_MUTE_ACTION_SUCCESS = 'CHANNEL_MUTE_ACTION_SUCCESS';
export const CHANNEL_MUTE_ACTION_FAILURE = 'CHANNEL_MUTE_ACTION_FAILURE';

export const CHANNEL_CREDENTIALS_GET_REQUEST = 'CHANNEL_CREDENTIALS_GET_REQUEST';
export const CHANNEL_CREDENTIALS_GET_SUCCESS = 'CHANNEL_CREDENTIALS_GET_SUCCESS';
export const CHANNEL_CREDENTIALS_GET_FAILURE = 'CHANNEL_CREDENTIALS_GET_FAILURE';

export const CHANNEL_CREDENTIALS_RENEW_REQUEST = 'CHANNEL_CREDENTIALS_RENEW_REQUEST';
export const CHANNEL_CREDENTIALS_RENEW_SUCCESS = 'CHANNEL_CREDENTIALS_RENEW_SUCCESS';
export const CHANNEL_CREDENTIALS_RENEW_FAILURE = 'CHANNEL_CREDENTIALS_RENEW_FAILURE';

export const CHANNEL_WEBHOOKS_GET_REQUEST = 'CHANNEL_WEBHOOKS_GET_REQUEST';
export const CHANNEL_WEBHOOKS_GET_SUCCESS = 'CHANNEL_WEBHOOKS_GET_SUCCESS';
export const CHANNEL_WEBHOOKS_GET_FAILURE = 'CHANNEL_WEBHOOKS_GET_FAILURE';

export const CHANNEL_WEBHOOKS_CREATE_REQUEST = 'CHANNEL_WEBHOOKS_CREATE_REQUEST';
export const CHANNEL_WEBHOOKS_CREATE_SUCCESS = 'CHANNEL_WEBHOOKS_CREATE_SUCCESS';
export const CHANNEL_WEBHOOKS_CREATE_FAILURE = 'CHANNEL_WEBHOOKS_CREATE_FAILURE';

export const CHANNEL_WEBHOOKS_DELETE_REQUEST = 'CHANNEL_WEBHOOKS_DELETE_REQUEST';
export const CHANNEL_WEBHOOKS_DELETE_SUCCESS = 'CHANNEL_WEBHOOKS_DELETE_SUCCESS';
export const CHANNEL_WEBHOOKS_DELETE_FAILURE = 'CHANNEL_WEBHOOKS_DELETE_FAILURE';

export const CHANNEL_WEBHOOKS_UPDATE_REQUEST = 'CHANNEL_WEBHOOKS_UPDATE_REQUEST';
export const CHANNEL_WEBHOOKS_UPDATE_SUCCESS = 'CHANNEL_WEBHOOKS_UPDATE_SUCCESS';
export const CHANNEL_WEBHOOKS_UPDATE_FAILURE = 'CHANNEL_WEBHOOKS_UPDATE_FAILURE';

export const CHANNEL_WHITELIST_ADD_REQUEST = 'CHANNEL_WHITELIST_ADD_REQUEST';
export const CHANNEL_WHITELIST_ADD_SUCCESS = 'CHANNEL_WHITELIST_ADD_SUCCESS';
export const CHANNEL_WHITELIST_ADD_FAILURE = 'CHANNEL_WHITELIST_ADD_FAILURE';

export const CHANNEL_WHITELIST_DELETE_REQUEST = 'CHANNEL_WHITELIST_DELETE_REQUEST';
export const CHANNEL_WHITELIST_DELETE_SUCCESS = 'CHANNEL_WHITELIST_DELETE_SUCCESS';
export const CHANNEL_WHITELIST_DELETE_FAILURE = 'CHANNEL_WHITELIST_DELETE_FAILURE';

export const CHANNEL_WHITELIST_UPDATE_REQUEST = 'CHANNEL_WHITELIST_UPDATE_REQUEST';
export const CHANNEL_WHITELIST_UPDATE_SUCCESS = 'CHANNEL_WHITELIST_UPDATE_SUCCESS';
export const CHANNEL_WHITELIST_UPDATE_FAILURE = 'CHANNEL_WHITELIST_UPDATE_FAILURE';

export const CHANNEL_WHITELIST_GET_REQUEST = 'CHANNEL_WHITELIST_GET_REQUEST';
export const CHANNEL_WHITELIST_GET_SUCCESS = 'CHANNEL_WHITELIST_GET_SUCCESS';
export const CHANNEL_WHITELIST_GET_FAILURE = 'CHANNEL_WHITELIST_GET_FAILURE';

export const CHANNEL_INACTIVATE_REQUEST = 'CHANNEL_INACTIVATE_REQUEST';
export const CHANNEL_INACTIVATE_SUCCESS = 'CHANNEL_INACTIVATE_SUCCESS';
export const CHANNEL_INACTIVATE_FAILURE = 'CHANNEL_INACTIVATE_FAILURE';

export const CHANNEL_ACTIVATE_REQUEST = 'CHANNEL_ACTIVATE_REQUEST';
export const CHANNEL_ACTIVATE_SUCCESS = 'CHANNEL_ACTIVATE_SUCCESS';
export const CHANNEL_ACTIVATE_FAILURE = 'CHANNEL_ACTIVATE_FAILURE';
